import type { Metadata } from 'next';
import './globals.css';
import { siteName, siteUrl } from '@/lib/config';
import { seoDescription, seoKeywords, siteGraph } from '@/lib/seo';
import { Analytics } from '@/components/Analytics';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: `${siteName} — Free online PDF imposition & prepress software`,
    template: `%s · ${siteName}`,
  },
  description: seoDescription,
  keywords: seoKeywords,
  applicationName: siteName,
  authors: [{ name: siteName }],
  creator: siteName,
  publisher: siteName,
  category: 'technology',
  alternates: { canonical: '/' },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  openGraph: {
    type: 'website',
    siteName,
    title: `${siteName} — Free online PDF imposition software`,
    description: seoDescription,
    url: siteUrl,
    locale: 'en_US',
    // OG/Twitter images are generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: 'summary_large_image',
    title: `${siteName} — Free online PDF imposition software`,
    description: seoDescription,
  },
  icons: { icon: '/favicon.svg' },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(siteGraph()) }}
        />
      </head>
      <body>{children}</body>
      <Analytics />
    </html>
  );
}
