import type { Metadata } from 'next';
import { Fraunces, Inter, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { siteName, siteUrl } from '@/lib/config';
import { seoDescription, seoKeywords, siteGraph } from '@/lib/seo';
import { Analytics } from '@/components/Analytics';

// Three faces, each with a job: Fraunces for the words that carry the page,
// Inter for everything read at length, JetBrains Mono for the numbers a
// printer actually cares about (215.9 × 279.4, 5.9 / 66.2, 1.5 mm).
const fraunces = Fraunces({
  subsets: ['latin'], style: ['normal', 'italic'], axes: ['opsz', 'SOFT'],
  variable: '--font-fraunces', display: 'swap',
});
const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap' });
const mono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-jbmono', display: 'swap' });

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: `${siteName} — press sheets from PDFs, in your browser`,
    template: `%s · ${siteName}`,
  },
  description: seoDescription,
  keywords: seoKeywords,
  applicationName: siteName,
  authors: [{ name: siteName }],
  creator: siteName,
  publisher: siteName,
  category: 'technology',
  alternates: { canonical: '/' },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  openGraph: {
    type: 'website',
    siteName,
    title: `${siteName} — press sheets from PDFs, in your browser`,
    description: seoDescription,
    url: siteUrl,
    locale: 'en_US',
    // OG/Twitter images are generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: 'summary_large_image',
    title: `${siteName} — press sheets from PDFs, in your browser`,
    description: seoDescription,
  },
  icons: { icon: '/favicon.svg' },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${fraunces.variable} ${inter.variable} ${mono.variable}`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(siteGraph()) }}
        />
      </head>
      <body>{children}</body>
      <Analytics />
    </html>
  );
}
