// Unified Template Library catalog — the single source of truth for the
// full-screen preset browser (see template-library.tsx). Every category and
// entry here is authored to match the product's reference spec exactly:
// category order, entry order, and the N-STEP badge (which equals the length
// of each entry's step chain). Each step maps to a real editor step type, so
// APPLY drops a working workflow into the press editor.
import type { StepType } from './steps';

export interface LibStep { type: StepType; s?: Record<string, unknown>; }
export interface LibEntry { id: string; name: string; desc: string; steps: LibStep[]; }
export interface LibCategory { name: string; entries: LibEntry[]; }

const S = (type: StepType, s?: Record<string, unknown>): LibStep => ({ type, ...(s ? { s } : {}) });
const e = (id: string, name: string, desc: string, steps: LibStep[]): LibEntry => ({ id, name, desc, steps });

export const LIBRARY: LibCategory[] = [
  // ── Commercial Print (50) ──────────────────────────────────────────────────
  { name: 'Commercial Print', entries: [
    e('cp-10up-bcards', '10-Up Business Cards', 'Standard US business cards (3.5×2") ganged 10-up on Letter with bleeds and crop marks.',
      [S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, bleedMode: 'fixed', bleedIn: 0.125, addMarks: true, centerMarks: true })]),
    e('cp-14up-bcards-tab', '14-Up Business Cards (Tabloid)', 'Production-run business cards ganged 14-up on 11×17" tabloid.',
      [S('grid', { cols: 2, rows: 7, cellWIn: 3.5, cellHIn: 2, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('cp-2up-postcards', '2-Up Postcards (4×6")', 'USPS-standard 4×6" postcards, 2-up (landscape) on Letter for short-run digital.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 6, cellHIn: 4, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-2up-rackcards', '2-Up Rack Cards (4×9")', 'Rack cards for brochure holders, 2-up on tabloid with die contour.',
      [S('grid', { cols: 2, rows: 1, cellWIn: 4, cellHIn: 9, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-trifold-2up', 'Tri-Fold Brochure 2-Up', 'Tri-fold brochures (11×8.5") 2-up on tabloid, with fold marks and trim contour.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'trifold' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-saddle-a5', 'Saddle-Stitch A5 Booklet', 'Print-ready A5 saddle-stitched booklet on A4 landscape sheets.',
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27, addMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-saddle-a4-mag', 'Saddle-Stitch A4 Magazine', 'A4 magazine signatures on A3 landscape with color bars and trim marks.',
      [S('booklet', { signatureSheets: 4, sheetWIn: 16.54, sheetHIn: 11.69, addMarks: true }), S('colorbar'), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-perfect-a5', 'Perfect Bound A5 Signatures', 'Perfect-bound A5 signatures with collating marks for the bindery.',
      [S('booklet', { signatureSheets: 4, addMarks: true }), S('collating')]),
    e('cp-steprepeat-flyer', 'Step-and-Repeat Flyer', 'Full-page flyer (8.5×11") stepped and repeated across the sheet.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 8.5, cellHIn: 11, order: 'repeat', sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-3up-num-tickets', '3-Up Numbered Tickets', 'Sequentially numbered raffle tickets (8×3.5"), 3-up with cut-and-stack ordering.',
      [S('datamerge'), S('shuffle'), S('grid', { cols: 1, rows: 3, cellWIn: 8, cellHIn: 3.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-2up-doorhangers', '2-Up Door Hangers', 'Door hangers (3.875×8.75") 2-up on Letter with die contour.',
      [S('grid', { cols: 2, rows: 1, cellWIn: 3.875, cellHIn: 8.75, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-tent-2up', 'Tent Card 2-Up', 'Folding tent cards (8×3.5" flat) 2-up with fold marks and cut contour.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 8, cellHIn: 3.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'half' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-letterhead-gang', 'Letterhead Gang Run', 'Multiple letterhead jobs (8.5×11") ganged 2-up on tabloid with press marks.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('colorbar'), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-playingcards-16', 'Playing Cards 16-Up', 'Full deck (2.5×3.5") imposed 16-up on 13×19" with front/back registration.',
      [S('grid', { cols: 4, rows: 4, cellWIn: 2.5, cellHIn: 3.5, sheetWIn: 13, sheetHIn: 19, addMarks: true, centerMarks: true }), S('regmarks'), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-round-coasters', 'Round Coasters (Nested)', 'Round drink coasters (4" dia) nested 6-up for die-cutting with contour marks.',
      [S('grid', { cols: 2, rows: 3, cellWIn: 4, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { shape: 'ellipse', cornersAndEdges: true })]),
    e('cp-eddm-postcard', 'EDDM Postcard (6.25×9")', 'USPS Every Door Direct Mail oversized postcard, 2-up on 13×19" stock.',
      [S('grid', { cols: 2, rows: 1, cellWIn: 6.25, cellHIn: 9, sheetWIn: 13, sheetHIn: 19, addMarks: true, centerMarks: true }), S('barcode')]),
    e('cp-certificate-2up', 'Certificate 2-Up', 'Award/training certificates (11×8.5") 2-up on tabloid with trim marks.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-wall-cal-sig', 'Wall Calendar Signatures', '13-page wall calendar imposed for saddle-stitch or wire-o binding.',
      [S('calendar', { addMarks: true }), S('booklet')]),
    e('cp-work-turn-gang', 'Work-and-Turn Gang Sheet', 'Work-and-turn duplex sheet (4-up) flipped along the long edge.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 5, cellHIn: 8, duplex: true, duplexFlip: 'long', sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-work-tumble-gang', 'Work-and-Tumble Gang Sheet', 'Work-and-tumble duplex sheet (4-up) flipped along the short edge.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 5, cellHIn: 8, duplex: true, duplexFlip: 'short', sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-cd-tray-2up', 'CD Tray Card 2-Up', 'CD jewel-case tray cards (5.9×4.6") 2-up on Letter.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 5.9, cellHIn: 4.6, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-shingled-3up', 'Shingled 3-Up (Cut & Stack)', 'Cut-and-stack imposition for sequentially ordered pieces (8×3.5"), 3 strips.',
      [S('cutstack', { cols: 1, rows: 3, cellWIn: 8, cellHIn: 3.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-trifold-letter', 'Tri-Fold Brochure (Letter)', 'Single tri-fold brochure on Letter landscape with fold marks.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 8.5, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'trifold' })]),
    e('cp-4up-rackcards', '4-Up Rack Cards (3.5×7")', 'Vertical rack cards (3.5×7") ganged 4-up on Tabloid.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 3.5, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('cp-3up-doorhangers', '3-Up Door Hangers', '3.5×8.5" door hangers ganged 3-up across on Tabloid.',
      [S('grid', { cols: 3, rows: 1, cellWIn: 3.5, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('cp-4up-ticket-strips', '4-Up Ticket Strips', 'Event/raffle tickets (8×2.5") stacked 4-up on Letter.',
      [S('grid', { cols: 1, rows: 4, cellWIn: 8, cellHIn: 2.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-ncr-3part', 'NCR Form (3-Part Carbon)', '3-part carbonless form (8.5×11") on Letter; each part on a separate sheet.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 8.5, cellHIn: 11, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-coupon-10up', 'Coupon Sheets (10-Up)', '3.5×2" coupons ganged 10-up on Letter with perforation marks.',
      [S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-2up-giftcert', '2-Up Gift Certificates (5×7")', '5×7" gift certificates, 2-up (landscape) on Letter with crop marks.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 7, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-2up-notepad', '2-Up Notepad Sheets', 'Half-letter notepads (5.5×8.5") printed 2-up on Letter landscape.',
      [S('grid', { cols: 2, rows: 1, cellWIn: 5.5, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 8.5, addMarks: true, centerMarks: true })]),
    e('cp-loyalty-10up', 'Loyalty/Punch Cards (10-Up)', 'Business-card-size (3.5×2") loyalty/punch cards, 10-up on Letter.',
      [S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-2up-invitation', '2-Up Invitation Cards (5×7")', 'Wedding/event invitations (5×7") 2-up (landscape) on Letter with bleeds.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 7, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, bleedMode: 'fixed', bleedIn: 0.125, addMarks: true, centerMarks: true })]),
    e('cp-photo-contact-8', 'Photo Contact Sheet (8-Up)', "Photographer's proof sheet with 8 images (2×4) on Letter.",
      [S('grid', { cols: 2, rows: 4, cellWIn: 3.75, cellHIn: 2.4, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-bifold-menu', 'Bi-Fold Restaurant Menu', 'Bi-fold menu on Tabloid — print both sides, fold for a 4-panel menu.',
      [S('booklet', { sheetWIn: 11, sheetHIn: 17, addMarks: true })]),
    e('cp-trifold-event', 'Tri-Fold Event Program', 'Tri-fold event program on Letter landscape with fold marks.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 8.5, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'trifold' })]),
    e('cp-rsvp-4up', 'RSVP Cards (4-Up A7)', 'A7 response/RSVP cards (3.5×5") printed 4-up on Letter with crop marks.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 3.5, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-sq-coasters-4', 'Square Coasters (4-Up)', '4" square coasters printed 4-up on Tabloid with die contour.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-tearoff-flyer', 'Tear-Off Flyer with Tabs', 'Flyer (8.5×11") with a row of tear-off contact tabs along the bottom.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 8.5, cellHIn: 11, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-folder-insert', 'Folder Insert (Tabloid)', 'Presentation folder insert (9×12") centered on tabloid with marks.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 9, cellHIn: 12, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('cp-checks-3up', 'Business Checks (3-Up)', 'Standard 3-up business checks (8×3.5") on Letter with MICR-safe layout.',
      [S('grid', { cols: 1, rows: 3, cellWIn: 8, cellHIn: 3.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode')]),
    e('cp-fullbleed-postcards', 'Full-Bleed Postcards (4-Up + Bleed)', 'Add 1/8" bleed to postcards (4×5"), then gang 4-up on Letter with crop marks.',
      [S('bleed', { bleedIn: 0.125 }), S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, bleedMode: 'fixed', bleedIn: 0.125, addMarks: true, centerMarks: true })]),
    e('cp-proof-sheet-wm', 'Proof Sheet with PROOF Watermark', '2-up proofing layout (11×8.5") on Tabloid with a diagonal PROOF watermark.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('watermark', { text: 'PROOF' })]),
    e('cp-fullbleed-brochure', 'Full-Bleed Brochure Booklet', 'Add 3mm bleed to brochure pages, then impose as a saddle-stitch booklet.',
      [S('bleed', { bleedIn: 0.125 }), S('booklet', { sheetWIn: 11, sheetHIn: 17, addMarks: true })]),
    e('cp-bcards-qr', 'Business Cards with QR Code', '10-up business cards (3.5×2") on Letter with a QR code stamped on the back.',
      [S('barcode', { symbology: 'qr' }), S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-bcard-8up-sr', 'Business Card 8-Up (Step & Repeat)', '8-up step-and-repeat business cards (3.5×2") — every slot prints the same card.',
      [S('grid', { cols: 2, rows: 4, cellWIn: 3.5, cellHIn: 2, order: 'repeat', sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-postcard-wt', 'Postcard 2-Up (Work & Turn)', '2-up work-and-turn postcard (6×4") imposition; flip along the short edge.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 6, cellHIn: 4, duplex: true, duplexFlip: 'long', sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-label-4up-cs', 'Label 4-Up (Cut & Stack)', 'Product labels (4×5") 4-up with cut-and-stack ordering for guillotining.',
      [S('cutstack', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-gatefold', 'Gatefold Brochure (4-Panel, Letter)', '4-panel gatefold brochure on Letter landscape with gate fold marks.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 8.5, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'gate' })]),
    e('cp-zfold', 'Z-Fold Accordion (6-Panel, Tabloid)', '6-panel Z-fold accordion on Tabloid landscape with fold marks.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 17, cellHIn: 11, sheetWIn: 17, sheetHIn: 11, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'zfold' })]),
    e('cp-comp-slips', 'Compliment Slips (DL 3-Up)', 'DL compliment slips (8.27×3.9") ganged 3-up on an SRA4 sheet.',
      [S('grid', { cols: 1, rows: 3, cellWIn: 8.27, cellHIn: 3.9, sheetWIn: 8.86, sheetHIn: 12.6, addMarks: true, centerMarks: true })]),
  ] },

  // ── Packaging (36) ─────────────────────────────────────────────────────────
  { name: 'Packaging', entries: [
    e('pk-folding-carton', 'Folding Carton Dieline', 'Folding carton box flat positioned on the die-line for die-cutting.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 9, cellHIn: 14, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { addDielines: true, cornersAndEdges: true })]),
    e('pk-sticker-a4', 'Sticker Sheet A4 (Die-Cut)', 'Full A4 sticker sheet with kiss-cut contours for peel-and-stick.',
      [S('stickers', { cols: 3, rows: 4, cellWIn: 2, cellHIn: 2.5, sheetWIn: 8.27, sheetHIn: 11.69, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-label-roll', 'Label Roll (Continuous)', 'Continuous roll labels with die lines and registration for a plotter.',
      [S('stickers', { cols: 1, rows: 5, cellWIn: 3, cellHIn: 2, sheetWIn: 4, sheetHIn: 12, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-hangtags-8up', 'Hang Tags 8-Up (2.5×4")', 'Retail hang tags (2.5×4") ganged 8-up with die contour and a barcode.',
      [S('grid', { cols: 2, rows: 4, cellWIn: 2.5, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true }), S('barcode')]),
    e('pk-wine-label-6', 'Wine Bottle Label 6-Up', 'Wine labels (3.5×4") 6-up with circumferential distortion and die marks.',
      [S('grid', { cols: 2, rows: 3, cellWIn: 3.5, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('distort'), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-blister-4up', 'Blister Card 4-Up', 'Retail blister-pack backing cards (5×7") 4-up with die and registration.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 5, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true }), S('regmarks')]),
    e('pk-soapbar-4up', 'Soap Bar Wrap 4-Up', 'Soap bar wraps (3×5") 4-up with fold marks and cut contour.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 3, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-envelope-flats', 'Envelope Flats 4-Up (#10)', '#10 envelope flats (9.5×4") 4-up with fold flaps and die lines.',
      [S('grid', { cols: 1, rows: 4, cellWIn: 9.5, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-retail-box-2up', 'Retail Box Flat 2-Up', 'Retail box flats (9×7") 2-up positioned on the die with cut contour.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 9, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-printcut-decals', 'Print & Cut Vinyl Decals', 'Print-and-cut vinyl decals nested with contour cut and registration.',
      [S('stickers', { cols: 3, rows: 4, cellWIn: 2.2, cellHIn: 2.2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-lp-sleeve', 'LP Record Sleeve Insert', '12.6×12.6" LP record sleeve insert with fold and trim marks.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 12, cellHIn: 12, sheetWIn: 12.6, sheetHIn: 12.6, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-pillbox', 'Pill Box Flat Pattern', 'Pharmaceutical pill-box carton flat with fold marks and die.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 6, cellHIn: 8, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-shopbag-2up', 'Shopping Bag Flat 2-Up', 'Paper shopping-bag flats (10×7") 2-up with gusset fold marks.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 10, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' })]),
    e('pk-pizza-lid', 'Pizza Box Lid (13×19")', 'Pizza box lid printed on 13×19" with fold and die-cut marks.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 12, cellHIn: 18, sheetWIn: 13, sheetHIn: 19, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-cereal-box', 'Cereal Box Flat', 'Folding cereal-carton flat (8×14") with cut contour on the die.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 8, cellHIn: 14, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-cd-jewel-wrap', 'CD/DVD Jewel Case Wrap', 'Jewel-case wrap and tray liner (9.5×4.75") with fold marks and die contour.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 9.5, cellHIn: 4.75, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-tea-box', 'Tea Box Wrap', 'Tea carton wrap flat (7×9") with cut contour for die-cutting.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 7, cellHIn: 9, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-cosmetic-box', 'Cosmetic Box Flats', 'Cosmetic folding-carton flats (4×6") 4-up positioned on the die with trim.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 6, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-seed-packets', 'Seed Packets (6-Up)', 'Seed packet flats (3.5×3") ganged 6-up on Letter.',
      [S('grid', { cols: 2, rows: 3, cellWIn: 3.5, cellHIn: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-candy-wrappers', 'Candy Bar Wrappers (3-Up)', 'Candy bar wraps (6×2.5") 3-up, sized to the standard bar circumference.',
      [S('grid', { cols: 1, rows: 3, cellWIn: 6, cellHIn: 2.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-bottleneck-6up', 'Bottle Neck Hangers (6-Up)', 'Die-cut bottle-neck hangers (3×4") 6-up with cut contour.',
      [S('grid', { cols: 2, rows: 3, cellWIn: 3, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-candle-wraps', 'Candle Wraps (4-Up)', 'Candle container wraps (8×2.5") ganged 4-up on Letter.',
      [S('grid', { cols: 1, rows: 4, cellWIn: 8, cellHIn: 2.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-soap-bands', 'Soap Band Wraps (8-Up)', 'Soap belly-band wraps (7×1.2") ganged 8-up on Letter.',
      [S('grid', { cols: 1, rows: 8, cellWIn: 7, cellHIn: 1.2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-giftbox-tab', 'Gift Box Flat (Tabloid)', 'Rigid gift-box flat (10×16") on Tabloid with cut contour.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 10, cellHIn: 16, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-pouch-2up', 'Pouch Flats (2-Up Tabloid)', 'Stand-up pouch flats (5×8") 2-up on Tabloid.',
      [S('grid', { cols: 2, rows: 1, cellWIn: 5, cellHIn: 8, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('pk-spice-labels', 'Spice Labels (Nested)', 'Spice-jar labels (2×1.5") nested for material efficiency with die lines.',
      [S('stickers', { cols: 3, rows: 5, cellWIn: 2, cellHIn: 1.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-shrink-sleeve', 'Shrink Sleeve (Roll)', 'Shrink sleeve at pre-shrink dimensions with distortion compensation.',
      [S('distort')]),
    e('pk-bakery-liner', 'Bakery Tray Liner (2-Up)', 'Grease-resistant bakery tray liners (10×7") 2-up.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 10, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('pk-corrugated', 'Corrugated Shipper Flat', 'Corrugated shipper box flat (10×16") with cut contour on the die.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 10, cellHIn: 16, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-polybag-headers', 'Poly Bag Headers (6-Up)', 'Header cards for poly bags (4×3") 6-up with die contour.',
      [S('grid', { cols: 2, rows: 3, cellWIn: 4, cellHIn: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-bottlecap-labels', 'Bottle Cap Labels (Nested)', 'Small round bottle-cap labels (1.2") nested with kiss-cut contour.',
      [S('stickers', { cols: 5, rows: 7, cellWIn: 1.2, cellHIn: 1.2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-tube-wrap-4up', 'Tube Label Wrap (4-Up)', 'Cosmetic tube wraps (6×2") 4-up with circumferential distortion.',
      [S('grid', { cols: 1, rows: 4, cellWIn: 6, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('distort')]),
    e('pk-product-bleed-bc', 'Product Labels with Bleed & Barcode', 'Add bleed, gang labels (3×4") 4-up, stamp a barcode, then add die lines.',
      [S('bleed', { bleedIn: 0.125 }), S('grid', { cols: 2, rows: 2, cellWIn: 3, cellHIn: 4, sheetWIn: 8.5, sheetHIn: 11, bleedMode: 'fixed', bleedIn: 0.125, addMarks: true, centerMarks: true }), S('barcode'), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-box-bleed-prep', 'Box Flat with Bleed Prep', 'Generate bleed on a box flat (8×11"), then add die-cut lines.',
      [S('bleed', { bleedIn: 0.125 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-carton-tuck', 'Folding Carton — Straight Tuck End', 'Straight-tuck-end folding carton flat (7×9") with cut contour.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 7, cellHIn: 9, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-presfolder-a4', 'Presentation Folder Dieline (A4 Pocket)', 'A4 presentation folder (8×11") with pocket, glue tabs and die lines.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 8, cellHIn: 11, sheetWIn: 8.27, sheetHIn: 11.69, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
  ] },

  // ── Publishing (37) ────────────────────────────────────────────────────────
  { name: 'Publishing', entries: [
    e('pb-trade-pb-4up', 'Perfect Bound Trade Paperback (4-Up)', 'Perfect-bound trade-paperback signatures, 4-up, with collating marks.',
      [S('booklet', { signatureSheets: 4 }), S('collating')]),
    e('pb-a6-mini-8up', 'Saddle-Stitch A6 Mini Booklet (8-Up)', 'A6 mini booklet imposed 8-up per sheet with fold marks.',
      [S('booklet', { sheetWIn: 8.27, sheetHIn: 11.69 }), S('foldmarks', { scheme: 'half' })]),
    e('pb-a5-sra3', 'A5 Saddle-Stitch 2-Up on SRA3', 'Impose A5 booklet flats, then repeat two copies on SRA3.',
      [S('booklet', { sheetWIn: 12.6, sheetHIn: 8.86 }), S('grid', { cols: 2, rows: 1, sheetWIn: 12.6, sheetHIn: 17.72 })]),
    e('pb-church-bulletin', '16-Page Church Bulletin (A4)', '16-page A4 saddle-stitch bulletin with trim marks.',
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 }), S('cuttermarks')]),
    e('pb-manga-rtl', 'Manga / RTL Comic Booklet', 'Right-to-left manga booklet with reversed page order and trim marks.',
      [S('booklet', { rtl: true }), S('cuttermarks')]),
    e('pb-landscape-wallcal', 'Landscape Wall Calendar', '13-page landscape wall calendar imposed for binding.',
      [S('calendar'), S('booklet')]),
    e('pb-desk-cal-tent', 'Desk Calendar (Tent Style)', 'Fold-and-stand tent desk calendar (13 pages).',
      [S('calendar')]),
    e('pb-32page-sig-8up', '32-Page Book Signature (8-Up)', '32-page book signatures 8-up with gathering and collating marks.',
      [S('booklet', { signatureSheets: 4 }), S('gathering'), S('collating')]),
    e('pb-digest-mag', 'Digest Magazine (5.5×8.5")', 'Digest-size magazine signatures with color bars and trim marks.',
      [S('booklet', { sheetWIn: 8.5, sheetHIn: 11 }), S('colorbar'), S('cuttermarks')]),
    e('pb-childrens', "Children's Picture Book", 'Full-color picture book signatures with color bars and trim marks.',
      [S('booklet', { signatureSheets: 4 }), S('colorbar'), S('cuttermarks')]),
    e('pb-layflat-photo', 'Lay-Flat Photo Book (12×12")', 'Lay-flat 12×12" photo book imposed as spreads with trim marks.',
      [S('booklet', { sheetWIn: 24, sheetHIn: 12 }), S('cuttermarks')]),
    e('pb-academic-4up', 'Academic Journal (4-Up)', 'Academic journal signatures 4-up with gathering and trim marks.',
      [S('booklet', { signatureSheets: 4 }), S('gathering'), S('cuttermarks')]),
    e('pb-newsletter-4pg', 'Newsletter 4-Page (Single Fold)', '4-page single-fold newsletter on Tabloid.',
      [S('booklet', { sheetWIn: 11, sheetHIn: 17 })]),
    e('pb-pocketbook-a6', 'Pocket Book (A6 from A5)', 'Scale A5 pages down to A6, impose as a booklet, add trim marks.',
      [S('resize'), S('booklet'), S('cuttermarks')]),
    e('pb-us-comic', 'US Comic Book (6.625×10.25")', 'US comic-book signatures with color bars and trim marks.',
      [S('booklet', { sheetWIn: 13.25, sheetHIn: 10.25 }), S('colorbar'), S('cuttermarks')]),
    e('pb-instr-a6-4up', 'Instruction Booklet (A6 4-Up)', 'A6 instruction booklet imposed 4-up per signature with trim marks.',
      [S('nupbook', { cols: 2, rows: 2 }), S('cuttermarks')]),
    e('pb-newspaper-tab', 'Newspaper Tabloid Signature', 'Tabloid newspaper signature imposition with trim marks.',
      [S('nupbook', { sheetWIn: 11, sheetHIn: 17 }), S('cuttermarks')]),
    e('pb-zine-8pg', 'One-Sheet 8-Page Zine', 'Single-sheet 8-page zine — print duplex, cut, and fold.',
      [S('zine')]),
    e('pb-zine-quarter', 'Quarter-Letter Zine', 'Quarter-letter mini zine folded from one sheet.',
      [S('zine')]),
    e('pb-a5-pocketbook', 'A5 Pocket Book', 'A5 pocket book saddle-stitched from A4 landscape sheets.',
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 })]),
    e('pb-playbill', 'Playbill / Theater Program', 'Saddle-stitch theater playbill / program.',
      [S('booklet')]),
    e('pb-recipe-book', 'Recipe Book (Letter)', 'Letter-size recipe book imposed for saddle-stitch binding.',
      [S('booklet', { sheetWIn: 11, sheetHIn: 8.5 })]),
    e('pb-wedding-program', 'Wedding Program', 'Folded wedding ceremony program.',
      [S('booklet')]),
    e('pb-memorial-program', 'Memorial / Funeral Program', 'Folded memorial / funeral service program.',
      [S('booklet')]),
    e('pb-yearbook-16up', 'Yearbook Signatures (16-Up)', 'Yearbook signatures imposed 16-up for perfect binding.',
      [S('nupbook', { cols: 4, rows: 4 })]),
    e('pb-hymnal-a5', 'Hymnal / Songbook (A5)', 'A5 hymnal / songbook saddle-stitched from A4 sheets.',
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 })]),
    e('pb-instr-manual-a5', 'Instruction Manual (A5)', 'A5 instruction manual imposed for saddle-stitch binding.',
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 })]),
    e('pb-pocket-digest', 'Pocket Digest (5×8")', 'Pocket digest (5×8") imposed for saddle-stitch binding.',
      [S('booklet', { sheetWIn: 10, sheetHIn: 8 })]),
    e('pb-concert-a5', 'Concert Program (A5)', 'A5 concert program booklet with trim marks.',
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 }), S('cuttermarks')]),
    e('pb-memorial-service', 'Memorial Service Program', 'Single-fold memorial service program.',
      [S('booklet')]),
    e('pb-student-planner', 'Student Planner (4-Up)', 'Student planner signatures imposed 4-up.',
      [S('nupbook', { cols: 2, rows: 2 })]),
    e('pb-coloring-book', 'Coloring Book (Letter)', 'Letter coloring book imposed for saddle-stitch with trim marks.',
      [S('booklet', { sheetWIn: 11, sheetHIn: 8.5 }), S('cuttermarks')]),
    e('pb-photo-book-a4', 'Photo Book (Landscape A4)', 'Landscape A4 photo book imposed as spreads with trim marks.',
      [S('booklet', { sheetWIn: 16.54, sheetHIn: 11.69 }), S('cuttermarks')]),
    e('pb-square-catalog', 'Square Catalog (8×8")', '8×8" square catalog signatures with trim marks.',
      [S('booklet', { sheetWIn: 16, sheetHIn: 8 }), S('cuttermarks')]),
    e('pb-8pg-saddle', '8-Page Saddle-Stitch Booklet', 'Simple 8-page saddle-stitch booklet.',
      [S('booklet')]),
    e('pb-16pg-perfect', '16-Page Signature (Perfect Bind)', '16-page signature imposed for perfect binding.',
      [S('nupbook')]),
    e('pb-trade-32pg', 'Trade Paperback 32-Page (Spine + Signatures)', '32-page trade paperback with spine allowance, gathering and collating marks.',
      [S('booklet', { signatureSheets: 4 }), S('gathering'), S('collating')]),
  ] },

  // ── Large Format (27) ──────────────────────────────────────────────────────
  { name: 'Large Format', entries: [
    e('lf-banner-tiles-4', 'Banner Tiles 4-Up (24×36")', 'Large banner split into 24×36" tiles for assembly.',
      [S('grid', { cols: 2, rows: 2, sheetWIn: 24, sheetHIn: 36, addMarks: true })]),
    e('lf-tiled-poster', 'Tiled Poster (A4 tiles to A0)', 'A0 poster tiled onto A4 sheets with overlap for assembly.',
      [S('grid', { sheetWIn: 8.27, sheetHIn: 11.69, addMarks: true })]),
    e('lf-roll-vinyl-24', 'Roll Vinyl Sticker Sheet (24")', '24" roll vinyl sticker sheet with contour cut and registration.',
      [S('stickers', { sheetWIn: 24 }), S('cuttermarks')]),
    e('lf-4up-18x24', '4-Up 18×24"', 'Four 18×24" posters ganged on an oversized sheet.',
      [S('grid', { cols: 2, rows: 2, sheetWIn: 36, sheetHIn: 48, addMarks: true })]),
    e('lf-steprepeat-photo', 'Step-and-Repeat Photo Print', 'Repeat a single photo print across a large-format sheet.',
      [S('grid', { order: 'repeat', addMarks: true })]),
    e('lf-wallpaper-27', 'Wallpaper Panel Repeat (27")', '27" wallpaper panels with a repeating pattern drop.',
      [S('resize', { sheetWIn: 27 })]),
    e('lf-2up-movie', '2-Up Movie Posters (27×40")', 'Two one-sheet movie posters (27×40") ganged on a wide sheet.',
      [S('grid', { cols: 1, rows: 2, sheetWIn: 27, sheetHIn: 80, addMarks: true })]),
    e('lf-label-roll-4', 'Label Roll 4"', '4" wide roll labels with contour cut and registration.',
      [S('stickers', { sheetWIn: 4 }), S('cuttermarks')]),
    e('lf-vehicle-wrap', 'Vehicle Wrap Panel Layout', 'Vehicle wrap split into overlapping panels for application.',
      [S('grid', { addMarks: true }), S('cuttermarks')]),
    e('lf-canvas-wrap', 'Canvas Wrap Print Tiling', 'Gallery-wrap canvas with mirrored edge wrap tiling.',
      [S('grid', { addMarks: true })]),
    e('lf-tradeshow', 'Trade Show Display Graphics', 'Multi-panel trade-show display split for print and assembly.',
      [S('grid', { addMarks: true }), S('cuttermarks')]),
    e('lf-billboard-4', 'Billboard Tiles (4-Panel)', 'Billboard artwork split into 4 printable panels.',
      [S('grid', { cols: 2, rows: 2, addMarks: true })]),
    e('lf-yardsigns-1824', 'Yard Signs (18×24")', 'Standard 18×24" yard sign scaled to size.',
      [S('resize', { sheetWIn: 18, sheetHIn: 24 })]),
    e('lf-re-signs-2436', 'Real Estate Signs (24×36")', '24×36" real-estate rider/panel sign scaled to size.',
      [S('resize', { sheetWIn: 24, sheetHIn: 36 })]),
    e('lf-menu-board', 'Menu Board (Tabloid)', 'Tabloid menu board scaled and prepped for large-format print.',
      [S('resize', { sheetWIn: 11, sheetHIn: 17 })]),
    e('lf-window-clings-a3', 'Window Clings (A3)', 'A3 static window clings scaled to size.',
      [S('resize', { sheetWIn: 11.69, sheetHIn: 16.54 })]),
    e('lf-floor-graphics', 'Floor Graphics (24×24")', '24×24" anti-slip floor graphic scaled to size.',
      [S('resize', { sheetWIn: 24, sheetHIn: 24 })]),
    e('lf-aframe-inserts', 'A-Frame Sign Inserts', 'Double-sided A-frame sidewalk sign inserts, 2-up.',
      [S('grid', { cols: 1, rows: 2, addMarks: true })]),
    e('lf-retractable', 'Retractable Banner (33×80")', '33×80" retractable roll-up banner scaled to size.',
      [S('resize', { sheetWIn: 33, sheetHIn: 80 })]),
    e('lf-exhibition-48', 'Exhibition Panel (4×8 ft)', '4×8 ft exhibition panel scaled and prepped.',
      [S('resize', { sheetWIn: 48, sheetHIn: 96 })]),
    e('lf-photo-backdrop', 'Photo Backdrop (8×10 ft)', '8×10 ft photo backdrop tiled for seamless assembly.',
      [S('grid', { sheetWIn: 96, sheetHIn: 120, addMarks: true })]),
    e('lf-table-runner', 'Table Runner (30×72")', '30×72" dye-sub table runner scaled to size.',
      [S('resize', { sheetWIn: 30, sheetHIn: 72 })]),
    e('lf-fabric-banner', 'Fabric Banner (24×72")', '24×72" fabric banner scaled to size.',
      [S('resize', { sheetWIn: 24, sheetHIn: 72 })]),
    e('lf-street-pole', 'Street Pole Banner (24×60")', '24×60" street-pole banner with pole-pocket allowance.',
      [S('resize', { sheetWIn: 24, sheetHIn: 60 })]),
    e('lf-bus-shelter', 'Bus Shelter Poster (46×67")', '46×67" bus-shelter poster scaled to size.',
      [S('resize', { sheetWIn: 46, sheetHIn: 67 })]),
    e('lf-yardsign-2418', 'Yard Sign (24×18")', 'Landscape 24×18" yard sign scaled to size.',
      [S('resize', { sheetWIn: 24, sheetHIn: 18 })]),
    e('lf-feather-flag', 'Feather Flag (Soft Signage)', 'Feather-flag soft-signage panel scaled to the flag profile.',
      [S('resize', { sheetWIn: 30, sheetHIn: 100 })]),
  ] },

  // ── Office (30) ────────────────────────────────────────────────────────────
  { name: 'Office', entries: [
    e('of-2sided-a5', '2-Sided A5 Flyer', 'Double-sided A5 flyer, 2-up on Letter.',
      [S('grid', { cols: 1, rows: 2, duplex: true, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-mini-a7-zine', 'Mini Booklet (A7 Zine)', 'A7 mini zine folded from a single sheet.',
      [S('zine')]),
    e('of-greeting-a5', 'Greeting Card (A5 Fold)', 'Half-fold A5 greeting card imposed for duplex printing.',
      [S('booklet')]),
    e('of-4up-index', '4-Up Index Cards (3×5")', '3×5" index cards 4-up on Letter with cut marks.',
      [S('grid', { cellWIn: 5, cellHIn: 3, sheetWIn: 8.5, sheetHIn: 11 }), S('cuttermarks')]),
    e('of-halfsheet-2up', 'Half-Sheet Handout 2-Up', 'Half-letter handouts 2-up on Letter.',
      [S('grid', { cols: 1, rows: 2, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-mailing-5160', 'Mailing Labels (Avery 5160 Style)', '30-up Avery 5160 address labels on Letter.',
      [S('grid', { cols: 3, rows: 10, cellWIn: 2.625, cellHIn: 1, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-add-pagenums', 'Add Page Numbers', 'Stamp folio / Bates page numbers on every page.',
      [S('pagenumbers')]),
    e('of-2up-proof-tab', '2-Up Proofing on Tabloid', 'Two document pages side by side on Tabloid with a PROOF watermark.',
      [S('grid', { cols: 1, rows: 2, sheetWIn: 11, sheetHIn: 17 }), S('watermark', { text: 'PROOF' })]),
    e('of-rotate-landscape', 'Rotate All Pages Landscape', 'Rotate every page 90° to landscape for the target press feed.',
      [S('rotate', { angleDeg: 90 })]),
    e('of-interleave', 'Interleave Two Documents', 'Interleave the pages of two PDFs one after another.',
      [S('mix')]),
    e('of-tent-cards-4', 'Tent Cards (4-Up)', 'Folding table tent cards 4-up on Letter.',
      [S('grid', { cols: 2, rows: 2, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-name-badges-8', 'Name Badges (8-Up)', 'Conference name badges 8-up on Letter.',
      [S('grid', { cols: 2, rows: 4, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-raffle-8up', 'Raffle Tickets (8-Up)', 'Raffle tickets 8-up on Letter.',
      [S('grid', { cols: 2, rows: 4, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-bookmarks-6', 'Bookmarks (6-Up)', 'Tall bookmarks ganged 6-up across a Letter sheet.',
      [S('grid', { cols: 6, rows: 1, sheetWIn: 11, sheetHIn: 8.5 })]),
    e('of-door-signs-2', 'Door Signs (2-Up)', 'Office door / room signs 2-up on Letter.',
      [S('grid', { cols: 1, rows: 2, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-deskplates-4', 'Desk Name Plates (4-Up)', 'Folding desk name plates 4-up on Letter.',
      [S('grid', { cols: 1, rows: 4, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-parking-4', 'Parking Permits (4-Up)', 'Parking permit hang cards 4-up on Letter.',
      [S('grid', { cols: 2, rows: 2, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-visitor-10', 'Visitor Passes (10-Up)', 'Visitor pass cards 10-up on Letter.',
      [S('grid', { cols: 2, rows: 5, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-flashcards-12', 'Flash Cards (12-Up)', 'Study flash cards 12-up on Letter.',
      [S('grid', { cols: 3, rows: 4, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-recipe-46', 'Recipe Cards (4×6")', '4×6" recipe cards 2-up on Letter.',
      [S('grid', { cellWIn: 4, cellHIn: 6, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-shipping-6', 'Shipping Labels (6-Up)', '4×6" shipping labels 6-up on Letter.',
      [S('grid', { cols: 2, rows: 3, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-place-cards-8', 'Place Cards (8-Up)', 'Folding place cards 8-up on Letter.',
      [S('grid', { cols: 2, rows: 4, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-luggage-6', 'Luggage Tags (6-Up)', 'Luggage tags 6-up on Letter.',
      [S('grid', { cols: 2, rows: 3, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-emergency-10', 'Emergency Contact Cards (10-Up)', 'Wallet emergency contact cards 10-up on Letter.',
      [S('grid', { cols: 2, rows: 5, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-spine-labels-10', 'Binder Spine Labels (10-Up)', 'Binder spine labels 10-up on Letter.',
      [S('grid', { cols: 2, rows: 5, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-certs-2', 'Certificates (2-Up)', 'Award certificates 2-up on Tabloid.',
      [S('grid', { cols: 1, rows: 2, sheetWIn: 11, sheetHIn: 17 })]),
    e('of-draft-wm', 'Draft Watermark', 'Stamp a diagonal DRAFT watermark across every page.',
      [S('watermark', { text: 'DRAFT' })]),
    e('of-confidential-wm', 'Confidential Watermark', 'Stamp a diagonal CONFIDENTIAL watermark across every page.',
      [S('watermark', { text: 'CONFIDENTIAL' })]),
    e('of-fullbleed-photocards', 'Full-Bleed Photo Cards (4×6")', 'Add bleed to 4×6" photo cards, then gang them on Letter.',
      [S('bleed', { bleedIn: 0.125 }), S('grid', { cellWIn: 4, cellHIn: 6, sheetWIn: 8.5, sheetHIn: 11 })]),
    e('of-proof-booklet-wm', 'Proof Booklet with Watermark', 'Impose a proof booklet and stamp a PROOF watermark on each page.',
      [S('booklet'), S('watermark', { text: 'PROOF' })]),
  ] },

  // ── Variable Data (10) ─────────────────────────────────────────────────────
  { name: 'Variable Data', entries: [
    e('vd-event-qr', 'Event Tickets (QR Code)', 'Event tickets with a unique QR code merged onto each cell.',
      [S('datamerge'), S('barcode', { symbology: 'qr' })]),
    e('vd-raffle-num', 'Raffle Tickets (Numbered)', 'Sequentially numbered raffle tickets with a Code 128 stub.',
      [S('datamerge'), S('barcode', { symbology: 'code128' })]),
    e('vd-conf-badges-qr', 'Conference Badges (QR)', 'Conference badges with attendee name and QR code merged in.',
      [S('datamerge'), S('barcode', { symbology: 'qr' })]),
    e('vd-shipping-c128', 'Shipping Labels (Code 128)', 'Shipping labels with a variable Code 128 tracking barcode.',
      [S('datamerge'), S('barcode', { symbology: 'code128' })]),
    e('vd-asset-dm', 'Asset Tags (DataMatrix)', 'Asset tags with a unique DataMatrix code per record.',
      [S('datamerge'), S('barcode', { symbology: 'datamatrix' })]),
    e('vd-product-ean13', 'Product Labels (EAN-13)', 'Retail product labels with a variable EAN-13 barcode.',
      [S('datamerge'), S('barcode', { symbology: 'ean13' })]),
    e('vd-gift-qr', 'Gift Vouchers (QR Code)', 'Gift vouchers with a unique redemption QR code.',
      [S('datamerge'), S('barcode', { symbology: 'qr' })]),
    e('vd-parking-qr', 'Parking Permits (QR Code)', 'Parking permits with a unique validation QR code.',
      [S('datamerge'), S('barcode', { symbology: 'qr' })]),
    e('vd-loyalty-c128', 'Loyalty Cards (Code 128)', 'Loyalty cards with a variable Code 128 member barcode.',
      [S('datamerge'), S('barcode', { symbology: 'code128' })]),
    e('vd-wristbands-qr', 'Wristbands (QR Code)', 'Event wristbands with a unique scannable QR code.',
      [S('datamerge'), S('barcode', { symbology: 'qr' })]),
  ] },

  // ── Real Estate (5) ────────────────────────────────────────────────────────
  { name: 'Real Estate', entries: [
    e('re-justlisted-4up', 'Just-Listed Flyer 4-Up (4.25×5.5")', 'Just-listed flyers (4.25×5.5") ganged 4-up on Letter.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 4.25, cellHIn: 5.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true })]),
    e('re-justlisted-2up', 'Just-Listed Flyer 2-Up (8.5×5.5")', 'Half-page just-listed flyers 2-up on Letter.',
      [S('grid', { cols: 1, rows: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true })]),
    e('re-justsold-4up', 'Just-Sold Postcard 4-Up (4×6")', 'Just-sold 4×6" postcards ganged 4-up on 13×19" stock.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 6, sheetWIn: 13, sheetHIn: 19, addMarks: true })]),
    e('re-brochure-trifold', 'Property Brochure Tri-Fold 2-Up', 'Property tri-fold brochures 2-up on Tabloid with fold marks.',
      [S('grid', { cols: 1, rows: 2, sheetWIn: 11, sheetHIn: 17, addMarks: true }), S('foldmarks', { scheme: 'trifold' })]),
    e('re-openhouse-yard', 'Open-House Yard Sign 2-Up (18×24")', 'Open-house directional yard signs (18×24") 2-up.',
      [S('grid', { cols: 1, rows: 2, sheetWIn: 18, sheetHIn: 48, addMarks: true })]),
  ] },
];
