// Unified Template Library catalog — the single source of truth for the
// full-screen preset browser (see template-library.tsx). Every category and
// entry here is authored to match the product's reference spec exactly:
// category order, entry order, and the N-STEP badge (which equals the length
// of each entry's step chain). Each step maps to a real editor step type, so
// APPLY drops a working workflow into the press editor.
import type { StepType } from './steps';

export interface LibStep { type: StepType; s?: Record<string, unknown>; }
export interface LibEntry { id: string; name: string; desc: string; steps: LibStep[]; }
export interface LibCategory { name: string; entries: LibEntry[]; }

const S = (type: StepType, s?: Record<string, unknown>): LibStep => ({ type, ...(s ? { s } : {}) });
const e = (id: string, name: string, desc: string, steps: LibStep[]): LibEntry => ({ id, name, desc, steps });

export const LIBRARY: LibCategory[] = [
  // ── Commercial Print (50) ──────────────────────────────────────────────────
  { name: 'Commercial Print', entries: [
    e('cp-10up-bcards', '10-Up Business Cards', "Standard US business cards (3.5×2\") ganged 10-up on Letter with bleeds and crop marks.",
      [S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, bleedMode: 'fixed', bleedIn: 0.125, addMarks: true, centerMarks: true })]),
    e('cp-14up-bcards-tab', '14-Up Business Cards (Tabloid)', "Production-run business cards ganged 14-up on 11×17\" tabloid for commercial offset.",
      [S('grid', { cols: 2, rows: 7, cellWIn: 3.5, cellHIn: 2, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('cp-2up-postcards', '2-Up Postcards (4×6")', "USPS-standard 4×6\" postcards, 2-up on Letter for desktop or short-run digital.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 6, cellHIn: 4, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-2up-rackcards', '2-Up Rack Cards (4×9")', "Standard rack cards for brochure holders, 2-up on tabloid stock.",
      [S('grid', { cols: 2, rows: 1, cellWIn: 4, cellHIn: 9, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-trifold-2up', 'Tri-Fold Brochure 2-Up', "Imposes two copies of each finished tri-fold brochure side on tabloid/A3-style duplex sheets.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'trifold' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-saddle-a5', 'Saddle-Stitch A5 Booklet', "Creates print-ready A5 saddle-stitched booklets from A5 source pages on A4 landscape sheets.",
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27, addMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-saddle-a4-mag', 'Saddle-Stitch A4 Magazine', "32-page A4 magazine signatures on A3 landscape sheets for commercial offset.",
      [S('booklet', { signatureSheets: 4, sheetWIn: 16.54, sheetHIn: 11.69, addMarks: true }), S('colorbar'), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-perfect-a5', 'Perfect Bound A5 Signatures', "4-up perfect-bound book signatures for A5 trade paperbacks on A4 landscape.",
      [S('booklet', { signatureSheets: 4, addMarks: true }), S('collating')]),
    e('cp-steprepeat-flyer', 'Step-and-Repeat Flyer', "Fill a sheet with sequential flyer pages, auto-scaled to fit. Ideal for different-content handouts.",
      [S('grid', { cols: 1, rows: 1, cellWIn: 8.5, cellHIn: 11, order: 'repeat', sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-3up-num-tickets', '3-Up Numbered Tickets', 'Sequentially numbered raffle tickets (8×3.5"), 3-up with cut-and-stack ordering.',
      [S('datamerge'), S('shuffle'), S('grid', { cols: 1, rows: 3, cellWIn: 8, cellHIn: 3.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-2up-doorhangers', '2-Up Door Hangers', "Standard door hangers (3.875×8.75\") ganged 2-up on Letter with trim marks.",
      [S('grid', { cols: 2, rows: 1, cellWIn: 3.875, cellHIn: 8.75, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-tent-2up', 'Tent Card 2-Up', "Fold-in-half table tent cards (4.25×5.5\" finished), 2-up on Letter for double-sided printing.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 8, cellHIn: 3.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'half' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-letterhead-gang', 'Letterhead Gang Run', 'Multiple letterhead jobs (8.5×11") ganged 2-up on tabloid with press marks.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('colorbar'), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-playingcards-16', 'Playing Cards 16-Up', 'Full deck (2.5×3.5") imposed 16-up on 13×19" with front/back registration.',
      [S('grid', { cols: 4, rows: 4, cellWIn: 2.5, cellHIn: 3.5, sheetWIn: 13, sheetHIn: 19, addMarks: true, centerMarks: true }), S('regmarks'), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-round-coasters', 'Round Coasters (Nested)', 'Round drink coasters (4" dia) nested 6-up for die-cutting with contour marks.',
      [S('grid', { cols: 2, rows: 3, cellWIn: 4, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { shape: 'ellipse', cornersAndEdges: true })]),
    e('cp-eddm-postcard', 'EDDM Postcard (6.25×9")', "USPS Every Door Direct Mail oversized postcard on 13×19\" stock.",
      [S('grid', { cols: 2, rows: 1, cellWIn: 6.25, cellHIn: 9, sheetWIn: 13, sheetHIn: 19, addMarks: true, centerMarks: true }), S('barcode')]),
    e('cp-certificate-2up', 'Certificate 2-Up', "Award or training certificates 2-up on tabloid for desktop proofing or short-run printing.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-wall-cal-sig', 'Wall Calendar Signatures', "Coil-bound wall calendar with back cover rotation on tabloid landscape.",
      [S('calendar', { addMarks: true }), S('booklet')]),
    e('cp-work-turn-gang', 'Work-and-Turn Gang Sheet', 'Work-and-turn duplex sheet (4-up) flipped along the long edge.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 5, cellHIn: 8, duplex: true, duplexFlip: 'long', sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-work-tumble-gang', 'Work-and-Tumble Gang Sheet', 'Work-and-tumble duplex sheet (4-up) flipped along the short edge.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 5, cellHIn: 8, duplex: true, duplexFlip: 'short', sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-cd-tray-2up', 'CD Tray Card 2-Up', "Standard CD jewel case tray cards (4.75×4.75\") ganged 2-up on Letter.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 5.9, cellHIn: 4.6, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-shingled-3up', 'Shingled 3-Up (Cut & Stack)', 'Cut-and-stack imposition for sequentially ordered pieces (8×3.5"), 3 strips.',
      [S('cutstack', { cols: 1, rows: 3, cellWIn: 8, cellHIn: 3.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-trifold-letter', 'Tri-Fold Brochure (Letter)', "Standard tri-fold brochure on Letter stock. 6 panels (3 front, 3 back) with fold marks.",
      [S('grid', { cols: 1, rows: 1, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 8.5, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'trifold' })]),
    e('cp-4up-rackcards', '4-Up Rack Cards (3.5×7")', 'Vertical rack cards (3.5×7") ganged 4-up on Tabloid.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 3.5, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('cp-3up-doorhangers', '3-Up Door Hangers', "3.5×8.5\" door hangers ganged 3-up across on Tabloid for die-cutting.",
      [S('grid', { cols: 3, rows: 1, cellWIn: 3.5, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('cp-4up-ticket-strips', '4-Up Ticket Strips', "Event/raffle tickets (8×2.5\") stacked 4-up on Letter with perforation marks.",
      [S('grid', { cols: 1, rows: 4, cellWIn: 8, cellHIn: 2.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-ncr-3part', 'NCR Form (3-Part Carbon)', "3-part carbonless form on Letter. Each part prints on separate sheet for collating.",
      [S('grid', { cols: 1, rows: 1, cellWIn: 8.5, cellHIn: 11, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-coupon-10up', 'Coupon Sheets (10-Up)', "3.5×2\" coupons ganged 10-up on Letter with perforation-ready marks.",
      [S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-2up-giftcert', '2-Up Gift Certificates (5×7")', "5×7\" gift certificates, 2-up on Letter stock with crop marks.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 7, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-2up-notepad', '2-Up Notepad Sheets', "Half-letter notepads (5.5×8.5\") printed 2-up on Letter (laid landscape) for padding.",
      [S('grid', { cols: 2, rows: 1, cellWIn: 5.5, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 8.5, addMarks: true, centerMarks: true })]),
    e('cp-loyalty-10up', 'Loyalty/Punch Cards (10-Up)', "Standard business-card-size loyalty/punch cards, 10-up on Letter with crop marks.",
      [S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-2up-invitation', '2-Up Invitation Cards (5×7")', "Wedding/event invitations (5×7\") printed 2-up on Letter with premium bleeds.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 7, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, bleedMode: 'fixed', bleedIn: 0.125, addMarks: true, centerMarks: true })]),
    e('cp-photo-contact-8', 'Photo Contact Sheet (8-Up)', "Photographer's proof sheet with 8 images (2×4) on Letter. Quick client review layout.",
      [S('grid', { cols: 2, rows: 4, cellWIn: 3.75, cellHIn: 2.4, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-bifold-menu', 'Bi-Fold Restaurant Menu', "Standard bi-fold menu on Tabloid. Print both sides, fold in half for 4-panel menu.",
      [S('booklet', { sheetWIn: 11, sheetHIn: 17, addMarks: true })]),
    e('cp-trifold-event', 'Tri-Fold Event Program', "Tri-fold event or church program on Letter landscape. 6 panels with fold marks.",
      [S('grid', { cols: 1, rows: 1, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 8.5, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'trifold' })]),
    e('cp-rsvp-4up', 'RSVP Cards (4-Up A7)', "Response/RSVP cards (3.5×5\") printed 4-up on Letter with crop marks.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 3.5, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-sq-coasters-4', 'Square Coasters (4-Up)', "4\" square drink coasters printed 4-up on Tabloid stock with crop marks for die cutting.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('cp-tearoff-flyer', 'Tear-Off Flyer with Tabs', 'Flyer (8.5×11") with a row of tear-off contact tabs along the bottom.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 8.5, cellHIn: 11, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-folder-insert', 'Folder Insert (Tabloid)', "Presentation folder insert (9×12\") centered on tabloid with trim marks.",
      [S('grid', { cols: 1, rows: 1, cellWIn: 9, cellHIn: 12, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('cp-checks-3up', 'Business Checks (3-Up)', "Standard 3-up business checks on Letter stock. MICR-safe layout with perforation marks.",
      [S('grid', { cols: 1, rows: 3, cellWIn: 8, cellHIn: 3.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode')]),
    e('cp-fullbleed-postcards', 'Full-Bleed Postcards (4-Up + Bleed)', "Add 1/8″ bleed to postcard artwork missing bleeds, then gang 4-up on Letter with crop marks.",
      [S('bleed', { bleedIn: 0.125 }), S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, bleedMode: 'fixed', bleedIn: 0.125, addMarks: true, centerMarks: true })]),
    e('cp-proof-sheet-wm', 'Proof Sheet with PROOF Watermark', '2-up proofing layout (11×8.5") on Tabloid with a diagonal PROOF watermark.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('watermark', { text: 'PROOF' })]),
    e('cp-fullbleed-brochure', 'Full-Bleed Brochure Booklet', "Add 3mm bleed to brochure pages, then impose as saddle-stitch booklet on Tabloid.",
      [S('bleed', { bleedIn: 0.125 }), S('booklet', { sheetWIn: 11, sheetHIn: 17, addMarks: true })]),
    e('cp-bcards-qr', 'Business Cards with QR Code', "10-up business cards on Letter with a QR code on the back — links to website or vCard.",
      [S('barcode', { symbology: 'qr' }), S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-bcard-8up-sr', 'Business Card 8-Up (Step & Repeat)', '8-up step-and-repeat business cards (3.5×2") — every slot prints the same card.',
      [S('grid', { cols: 2, rows: 4, cellWIn: 3.5, cellHIn: 2, order: 'repeat', sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-postcard-wt', 'Postcard 2-Up (Work & Turn)', '2-up work-and-turn postcard (6×4") imposition; flip along the short edge.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 6, cellHIn: 4, duplex: true, duplexFlip: 'long', sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-label-4up-cs', 'Label 4-Up (Cut & Stack)', 'Product labels (4×5") 4-up with cut-and-stack ordering for guillotining.',
      [S('cutstack', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('cp-gatefold', 'Gatefold Brochure (4-Panel, Letter)', "4-panel gatefold marketing brochure on Letter landscape. Two inner panels fold inward to meet at center.",
      [S('grid', { cols: 1, rows: 1, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 8.5, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'gate' })]),
    e('cp-zfold', 'Z-Fold Accordion (6-Panel, Tabloid)', "6-panel accordion-style brochure on 11×17\" tabloid. Zigzag folds, ~5.67\" per panel (17/3).",
      [S('grid', { cols: 1, rows: 1, cellWIn: 17, cellHIn: 11, sheetWIn: 17, sheetHIn: 11, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'zfold' })]),
    e('cp-comp-slips', 'Compliment Slips (DL 3-Up)', 'DL compliment slips (8.27×3.9") ganged 3-up on an SRA4 sheet.',
      [S('grid', { cols: 1, rows: 3, cellWIn: 8.27, cellHIn: 3.9, sheetWIn: 8.86, sheetHIn: 12.6, addMarks: true, centerMarks: true })]),
  ] },

  // ── Packaging (36) ─────────────────────────────────────────────────────────
  { name: 'Packaging', entries: [
    e('pk-folding-carton', 'Folding Carton Dieline', 'Folding carton box flat positioned on the die-line for die-cutting.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 9, cellHIn: 14, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { addDielines: true, cornersAndEdges: true })]),
    e('pk-sticker-a4', 'Sticker Sheet A4 (Die-Cut)', 'Full A4 sticker sheet with kiss-cut contours for peel-and-stick.',
      [S('stickers', { cols: 3, rows: 4, cellWIn: 2, cellHIn: 2.5, sheetWIn: 8.27, sheetHIn: 11.69, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-label-roll', 'Label Roll (Continuous)', 'Continuous roll labels with die lines and registration for a plotter.',
      [S('stickers', { cols: 1, rows: 5, cellWIn: 3, cellHIn: 2, sheetWIn: 4, sheetHIn: 12, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-hangtags-8up', 'Hang Tags 8-Up (2.5×4")', "Retail garment hang tags ganged 8-up on Tabloid with die-cut contour paths.",
      [S('grid', { cols: 2, rows: 4, cellWIn: 2.5, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true }), S('barcode')]),
    e('pk-wine-label-6', 'Wine Bottle Label 6-Up', "Standard wine bottle labels (3.5×4\") ganged 6-up on Tabloid with trim marks.",
      [S('grid', { cols: 2, rows: 3, cellWIn: 3.5, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('distort'), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-blister-4up', 'Blister Card 4-Up', "Retail blister packaging cards (3.5×5\") ganged 4-up on Tabloid with dieline paths.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 5, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true }), S('regmarks')]),
    e('pk-soapbar-4up', 'Soap Bar Wrap 4-Up', "Body care product wraps (3×4\") ganged 4-up on Letter.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 3, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-envelope-flats', 'Envelope Flats 4-Up (#10)', "Standard #10 envelope flats (9.5×4.125\") ganged 4-up on Tabloid with dieline paths.",
      [S('grid', { cols: 1, rows: 4, cellWIn: 9.5, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-retail-box-2up', 'Retail Box Flat 2-Up', 'Retail box flats (9×7") 2-up positioned on the die with cut contour.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 9, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-printcut-decals', 'Print & Cut Vinyl Decals', 'Print-and-cut vinyl decals nested with contour cut and registration.',
      [S('stickers', { cols: 3, rows: 4, cellWIn: 2.2, cellHIn: 2.2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-lp-sleeve', 'LP Record Sleeve Insert', "12×12\" vinyl record sleeve insert, 1-up on 13×19\" stock (12″ square cannot fit 2-up on a 13×19″ sheet).",
      [S('grid', { cols: 1, rows: 1, cellWIn: 12, cellHIn: 12, sheetWIn: 12.6, sheetHIn: 12.6, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-pillbox', 'Pill Box Flat Pattern', 'Pharmaceutical pill-box carton flat with fold marks and die.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 6, cellHIn: 8, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-shopbag-2up', 'Shopping Bag Flat 2-Up', "Retail shopping bag flats 2-up on Tabloid with fold and die-cut paths.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 10, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' })]),
    e('pk-pizza-lid', 'Pizza Box Lid (13×19")', "10×10\" pizza box lid flat, 1-up on 13×19\" stock with trim marks (10″ square cannot fit 2-up).",
      [S('grid', { cols: 1, rows: 1, cellWIn: 12, cellHIn: 18, sheetWIn: 13, sheetHIn: 19, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-cereal-box', 'Cereal Box Flat', 'Folding cereal-carton flat (8×14") with cut contour on the die.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 8, cellHIn: 14, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-cd-jewel-wrap', 'CD/DVD Jewel Case Wrap', "Optical disc jewel case wrap (9.5×4.72\") on Tabloid with trim marks.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 9.5, cellHIn: 4.75, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'custom' }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-tea-box', 'Tea Box Wrap', 'Tea carton wrap flat (7×9") with cut contour for die-cutting.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 7, cellHIn: 9, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-cosmetic-box', 'Cosmetic Box Flats', 'Cosmetic folding-carton flats (4×6") 4-up positioned on the die with trim.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 6, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-seed-packets', 'Seed Packets (6-Up)', 'Seed packet flats (3.5×3") ganged 6-up on Letter.',
      [S('grid', { cols: 2, rows: 3, cellWIn: 3.5, cellHIn: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-candy-wrappers', 'Candy Bar Wrappers (3-Up)', "Candy bar wraps (7.5×5.5\") placed 3-up on a 13×19″ press sheet for wrapping and gluing.",
      [S('grid', { cols: 1, rows: 3, cellWIn: 6, cellHIn: 2.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-bottleneck-6up', 'Bottle Neck Hangers (6-Up)', 'Die-cut bottle-neck hangers (3×4") 6-up with cut contour.',
      [S('grid', { cols: 2, rows: 3, cellWIn: 3, cellHIn: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-candle-wraps', 'Candle Wraps (4-Up)', "Candle label wraps (3×8\") printed 4-up on Tabloid for wrapping round candles.",
      [S('grid', { cols: 1, rows: 4, cellWIn: 8, cellHIn: 2.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-soap-bands', 'Soap Band Wraps (8-Up)', 'Soap belly-band wraps (7×1.2") ganged 8-up on Letter.',
      [S('grid', { cols: 1, rows: 8, cellWIn: 7, cellHIn: 1.2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-giftbox-tab', 'Gift Box Flat (Tabloid)', 'Rigid gift-box flat (10×16") on Tabloid with cut contour.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 10, cellHIn: 16, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-pouch-2up', 'Pouch Flats (2-Up Tabloid)', "Stand-up pouch flats (6×9\") printed 2-up on landscape Tabloid for heat-seal pouches.",
      [S('grid', { cols: 2, rows: 1, cellWIn: 5, cellHIn: 8, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('pk-spice-labels', 'Spice Labels (Nested)', 'Spice-jar labels (2×1.5") nested for material efficiency with die lines.',
      [S('stickers', { cols: 3, rows: 5, cellWIn: 2, cellHIn: 1.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-shrink-sleeve', 'Shrink Sleeve (Roll)', 'Shrink sleeve at pre-shrink dimensions with distortion compensation.',
      [S('distort')]),
    e('pk-bakery-liner', 'Bakery Tray Liner (2-Up)', "Bakery/deli tray liners printed 1-up on Tabloid (two 10.5″ liners cannot stack on a 17″ sheet).",
      [S('grid', { cols: 1, rows: 2, cellWIn: 10, cellHIn: 7, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('pk-corrugated', 'Corrugated Shipper Flat', 'Corrugated shipper box flat (10×16") with cut contour on the die.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 10, cellHIn: 16, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-polybag-headers', 'Poly Bag Headers (6-Up)', "Retail poly bag header cards (4×2.5\") printed 6-up on Letter with hang-hole marks.",
      [S('grid', { cols: 2, rows: 3, cellWIn: 4, cellHIn: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-bottlecap-labels', 'Bottle Cap Labels (Nested)', 'Small round bottle-cap labels (1.2") nested with kiss-cut contour.',
      [S('stickers', { cols: 5, rows: 7, cellWIn: 1.2, cellHIn: 1.2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('pk-tube-wrap-4up', 'Tube Label Wrap (4-Up)', "Cosmetic tube label wraps (6×2.5\") printed 4-up on a 13×19″ sheet for roll-on application.",
      [S('grid', { cols: 1, rows: 4, cellWIn: 6, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('distort')]),
    e('pk-product-bleed-bc', 'Product Labels with Bleed & Barcode', 'Add bleed, gang labels (3×4") 4-up, stamp a barcode, then add die lines.',
      [S('bleed', { bleedIn: 0.125 }), S('grid', { cols: 2, rows: 2, cellWIn: 3, cellHIn: 4, sheetWIn: 8.5, sheetHIn: 11, bleedMode: 'fixed', bleedIn: 0.125, addMarks: true, centerMarks: true }), S('barcode'), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-box-bleed-prep', 'Box Flat with Bleed Prep', "Add 5mm bleed to a box dieline flat, then resize to fit press sheet — ready for die-cutting.",
      [S('bleed', { bleedIn: 0.125 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-carton-tuck', 'Folding Carton — Straight Tuck End', 'Straight-tuck-end folding carton flat (7×9") with cut contour.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 7, cellHIn: 9, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pk-presfolder-a4', 'Presentation Folder Dieline (A4 Pocket)', 'A4 presentation folder (8×11") with pocket, glue tabs and die lines.',
      [S('grid', { cols: 1, rows: 1, cellWIn: 8, cellHIn: 11, sheetWIn: 8.27, sheetHIn: 11.69, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
  ] },

  // ── Publishing (37) ────────────────────────────────────────────────────────
  { name: 'Publishing', entries: [
    e('pb-trade-pb-4up', 'Perfect Bound Trade Paperback (4-Up)', "4-up signatures for A5 perfect-bound trade paperbacks. Standard for novels, manuals, and catalogs.",
      [S('booklet', { signatureSheets: 4 }), S('collating')]),
    e('pb-a6-mini-8up', 'Saddle-Stitch A6 Mini Booklet (8-Up)', "8-up mini booklet for A6 saddle-stitched inserts and leaflets on A4.",
      [S('booklet', { sheetWIn: 8.27, sheetHIn: 11.69 }), S('foldmarks', { scheme: 'half' })]),
    e('pb-a5-sra3', 'A5 Saddle-Stitch 2-Up on SRA3', "Commercial A5 saddle-stitch workflow: impose each booklet side on SRA4, then repeat two copies on SRA3.",
      [S('booklet', { sheetWIn: 12.6, sheetHIn: 8.86 }), S('grid', { cols: 2, rows: 1, sheetWIn: 12.6, sheetHIn: 17.72 })]),
    e('pb-church-bulletin', '16-Page Church Bulletin (A4)', "Saddle-stitched A4 bulletin on A3 landscape. Standard for weekly church programs.",
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-manga-rtl', 'Manga / RTL Comic Booklet', "Right-to-left saddle-stitched booklet for manga, Arabic, and Hebrew comics on B5 landscape.",
      [S('booklet', { rtl: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-landscape-wallcal', 'Landscape Wall Calendar', "Coil-bound wall calendar with back cover rotation on Tabloid landscape.",
      [S('calendar'), S('booklet')]),
    e('pb-desk-cal-tent', 'Desk Calendar (Tent Style)', "Desk tent calendar on Letter landscape with half-sheet layout.",
      [S('calendar')]),
    e('pb-32page-sig-8up', '32-Page Book Signature (8-Up)', '32-page book signatures 8-up with gathering and collating marks.',
      [S('booklet', { signatureSheets: 4 }), S('gathering'), S('collating')]),
    e('pb-digest-mag', 'Digest Magazine (5.5×8.5")', "Reader's Digest-size magazine signatures. 4-up saddle-stitch on Tabloid.",
      [S('booklet', { sheetWIn: 8.5, sheetHIn: 11 }), S('colorbar'), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-childrens', "Children's Picture Book", 'Full-color picture book signatures with color bars and trim marks.',
      [S('booklet', { signatureSheets: 4 }), S('colorbar'), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-layflat-photo', 'Lay-Flat Photo Book (12×12")', "Square photo album with zero creep for lay-flat binding on 24×12\" stock.",
      [S('booklet', { sheetWIn: 24, sheetHIn: 12 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-academic-4up', 'Academic Journal (4-Up)', 'Academic journal signatures 4-up with gathering and trim marks.',
      [S('booklet', { signatureSheets: 4 }), S('gathering'), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-newsletter-4pg', 'Newsletter 4-Page (Single Fold)', "Simple 4-page newsletter — one sheet folded in half on Letter landscape.",
      [S('booklet', { sheetWIn: 11, sheetHIn: 17 })]),
    e('pb-pocketbook-a6', 'Pocket Book (A6 from A5)', "Small-format pocket book in A6 with 2-up perfect binding.",
      [S('resize'), S('booklet'), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-us-comic', 'US Comic Book (6.625×10.25")', "Standard US comic book format on Tabloid with saddle-stitch binding.",
      [S('booklet', { sheetWIn: 13.25, sheetHIn: 10.25 }), S('colorbar'), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-instr-a6-4up', 'Instruction Booklet (A6 4-Up)', "Small product instruction booklet. 4-up nested on A4 for cost-effective production.",
      [S('nupbook', { cols: 2, rows: 2 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-newspaper-tab', 'Newspaper Tabloid Signature', 'Tabloid newspaper signature imposition with trim marks.',
      [S('nupbook', { sheetWIn: 11, sheetHIn: 17 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-zine-8pg', 'One-Sheet 8-Page Zine', 'Single-sheet 8-page zine — print duplex, cut, and fold.',
      [S('zine')]),
    e('pb-zine-quarter', 'Quarter-Letter Zine', "Micro-zine at 4.25×5.5\" using 4-up saddle-stitch on Letter. Cut, fold, staple.",
      [S('zine')]),
    e('pb-a5-pocketbook', 'A5 Pocket Book', "A5 (148×210mm) pocket paperback using saddle-stitch binding on A4 landscape.",
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 })]),
    e('pb-playbill', 'Playbill / Theater Program', "A5 saddle-stitched theater program booklet on A4 stock.",
      [S('booklet', { addMarks: true })]),
    e('pb-recipe-book', 'Recipe Book (Letter)', "US Letter recipe book with perfect binding. Ideal for cookbooks and recipe collections.",
      [S('booklet', { sheetWIn: 11, sheetHIn: 8.5 })]),
    e('pb-wedding-program', 'Wedding Program', "Half-letter (5.5×8.5\") wedding program booklet, saddle-stitched on Letter landscape.",
      [S('booklet', { addMarks: true })]),
    e('pb-memorial-program', 'Memorial / Funeral Program', "Half-letter memorial program, saddle-stitched on Letter landscape. Single fold, 4-8 pages.",
      [S('booklet', { addMarks: true })]),
    e('pb-yearbook-16up', 'Yearbook Signatures (16-Up)', 'Yearbook signatures imposed 16-up for perfect binding.',
      [S('nupbook', { cols: 4, rows: 4 })]),
    e('pb-hymnal-a5', 'Hymnal / Songbook (A5)', "A5 hymnal or songbook with perfect binding on A4 stock. For churches and choirs.",
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 })]),
    e('pb-instr-manual-a5', 'Instruction Manual (A5)', "A5 product instruction booklet, saddle-stitched on A4. Compact format for product packaging.",
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 })]),
    e('pb-pocket-digest', 'Pocket Digest (5×8")', "5×8\" digest-size booklet using perfect binding. Common for literary journals and anthologies.",
      [S('booklet', { sheetWIn: 10, sheetHIn: 8 })]),
    e('pb-concert-a5', 'Concert Program (A5)', "A5 saddle-stitched concert or theater program. 12-16 pages typical, fits in pocket.",
      [S('booklet', { sheetWIn: 11.69, sheetHIn: 8.27 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-memorial-service', 'Memorial Service Program', "Half-letter bi-fold memorial program. 4 pages — cover, obituary spread, back.",
      [S('booklet', { addMarks: true })]),
    e('pb-student-planner', 'Student Planner (4-Up)', "A6 student planner pages imposed 4-up on A4 for perfect binding. 52+ weeks.",
      [S('nupbook', { cols: 2, rows: 2 })]),
    e('pb-coloring-book', 'Coloring Book (Letter)', "US Letter coloring book with saddle-stitch binding. Single-sided interior (back pages blank).",
      [S('booklet', { sheetWIn: 11, sheetHIn: 8.5 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-photo-book-a4', 'Photo Book (Landscape A4)', "Landscape A4 photo book with perfect binding. Full-bleed photo spreads.",
      [S('booklet', { sheetWIn: 16.54, sheetHIn: 11.69 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-square-catalog', 'Square Catalog (8×8")', "8×8\" square product catalog with saddle-stitch binding. Popular for retail and portfolio.",
      [S('booklet', { sheetWIn: 16, sheetHIn: 8 }), S('cuttermarks', { cornersAndEdges: true })]),
    e('pb-8pg-saddle', '8-Page Saddle-Stitch Booklet', 'Simple 8-page saddle-stitch booklet.',
      [S('booklet', { addMarks: true })]),
    e('pb-16pg-perfect', '16-Page Signature (Perfect Bind)', '16-page signature imposed for perfect binding.',
      [S('nupbook')]),
    e('pb-trade-32pg', 'Trade Paperback 32-Page (Spine + Signatures)', '32-page trade paperback with spine allowance, gathering and collating marks.',
      [S('booklet', { signatureSheets: 4 }), S('gathering'), S('collating')]),
  ] },

  // ── Large Format (27) ──────────────────────────────────────────────────────
  { name: 'Large Format', entries: [
    e('lf-banner-tiles-4', 'Banner Tiles 4-Up (24×36")', "Four 24×36\" banner panels on a single 96×36\" wide-format sheet for trade show displays.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 12, cellHIn: 18, sheetWIn: 24, sheetHIn: 36, addMarks: true, centerMarks: true })]),
    e('lf-tiled-poster', 'Tiled Poster (A4 tiles to A0)', "Tiles a large poster across multiple sheets. Each source page fills one cell in an 4×2 grid.",
      [S('grid', { cols: 2, rows: 4, sheetWIn: 16.54, sheetHIn: 23.4, addMarks: true, centerMarks: true })]),
    e('lf-roll-vinyl-24', 'Roll Vinyl Sticker Sheet (24")', '24" roll vinyl sticker sheet with contour cut and registration.',
      [S('stickers', { cols: 4, rows: 5, cellWIn: 5, cellHIn: 5, sheetWIn: 24, sheetHIn: 36, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('lf-4up-18x24', '4-Up 18×24"', 'Four 18×24" posters ganged on an oversized sheet.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 18, cellHIn: 24, sheetWIn: 36, sheetHIn: 48, addMarks: true, centerMarks: true })]),
    e('lf-steprepeat-photo', 'Step-and-Repeat Photo Print', "Fill a sheet with identical photos. Perfect for passport photos, photo booth strips, and proofing.",
      [S('grid', { cols: 2, rows: 3, cellWIn: 5, cellHIn: 7, order: 'repeat', sheetWIn: 13, sheetHIn: 24, addMarks: true, centerMarks: true })]),
    e('lf-wallpaper-27', 'Wallpaper Panel Repeat (27")', '27"-wide wallpaper panels with a repeating pattern drop.',
      [S('resize', { sheetWIn: 27, sheetHIn: 120, addMarks: true, centerMarks: true })]),
    e('lf-2up-movie', '2-Up Movie Posters (27×40")', "Standard one-sheet cinema posters ganged 2-up on 54×40\" wide-format stock.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 27, cellHIn: 40, sheetWIn: 27, sheetHIn: 80, addMarks: true, centerMarks: true })]),
    e('lf-label-roll-4', 'Label Roll 4"', '4"-wide roll labels with contour cut and registration.',
      [S('stickers', { cols: 1, rows: 6, cellWIn: 3, cellHIn: 2, sheetWIn: 4, sheetHIn: 14, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('lf-vehicle-wrap', 'Vehicle Wrap Panel Layout', 'Vehicle wrap split into overlapping panels for application.',
      [S('grid', { cols: 3, rows: 2, cellWIn: 20, cellHIn: 30, sheetWIn: 60, sheetHIn: 60, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('lf-canvas-wrap', 'Canvas Wrap Print Tiling', "Gallery-wrap canvas tiles auto-scaled in a 2×2 grid for large art prints.",
      [S('grid', { cols: 1, rows: 1, cellWIn: 20, cellHIn: 20, sheetWIn: 24, sheetHIn: 24, addMarks: true, centerMarks: true })]),
    e('lf-tradeshow', 'Trade Show Display Graphics', "Exhibition pop-up display panels on 48×96\" wide-format with color bar for proofing.",
      [S('grid', { cols: 3, rows: 1, cellWIn: 30, cellHIn: 90, sheetWIn: 96, sheetHIn: 96, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('lf-billboard-4', 'Billboard Tiles (4-Panel)', 'Billboard artwork split into 4 printable panels.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 24, cellHIn: 12, sheetWIn: 48, sheetHIn: 24, addMarks: true, centerMarks: true })]),
    e('lf-yardsigns-1824', 'Yard Signs (18×24")', "Corrugated yard signs at 18×24\" for real estate, political campaigns, and event signage.",
      [S('resize', { sheetWIn: 18, sheetHIn: 24, addMarks: true, centerMarks: true })]),
    e('lf-re-signs-2436', 'Real Estate Signs (24×36")', "Large real estate signs at 24×36\" for property listings and open house signage.",
      [S('resize', { sheetWIn: 24, sheetHIn: 36, addMarks: true, centerMarks: true })]),
    e('lf-menu-board', 'Menu Board (Tabloid)', "Restaurant menu board at 11×17\" Tabloid with color bar for print verification.",
      [S('resize', { sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('lf-window-clings-a3', 'Window Clings (A3)', "A3 (297×420mm) window cling graphics for storefront and vehicle windows.",
      [S('resize', { sheetWIn: 11.69, sheetHIn: 16.54, addMarks: true, centerMarks: true })]),
    e('lf-floor-graphics', 'Floor Graphics (24×24")', "Square floor decals at 24×24\" for retail wayfinding and promotional graphics.",
      [S('resize', { sheetWIn: 24, sheetHIn: 24, addMarks: true, centerMarks: true })]),
    e('lf-aframe-inserts', 'A-Frame Sign Inserts', "Sidewalk A-frame sign inserts at 24×36\" with double-sided printing.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 24, cellHIn: 18, sheetWIn: 24, sheetHIn: 36, addMarks: true, centerMarks: true })]),
    e('lf-retractable', 'Retractable Banner (33×80")', "Standard retractable/roll-up banner at 33×80\" for trade shows and events.",
      [S('resize', { sheetWIn: 33, sheetHIn: 80, addMarks: true, centerMarks: true })]),
    e('lf-exhibition-48', 'Exhibition Panel (4×8 ft)', '4×8 ft exhibition panel scaled and prepped.',
      [S('resize', { sheetWIn: 48, sheetHIn: 96, addMarks: true, centerMarks: true })]),
    e('lf-photo-backdrop', 'Photo Backdrop (8×10 ft)', '8×10 ft photo backdrop tiled for seamless assembly.',
      [S('grid', { cols: 2, rows: 2, cellWIn: 48, cellHIn: 60, sheetWIn: 96, sheetHIn: 120, addMarks: true, centerMarks: true })]),
    e('lf-table-runner', 'Table Runner (30×72")', "Conference table runner at 30×72\" for 6ft tables. Resized for large-format output.",
      [S('resize', { sheetWIn: 30, sheetHIn: 72, addMarks: true, centerMarks: true })]),
    e('lf-fabric-banner', 'Fabric Banner (24×72")', "Vertical fabric banner at 24×72\" for dye-sublimation printing.",
      [S('resize', { sheetWIn: 24, sheetHIn: 72, addMarks: true, centerMarks: true })]),
    e('lf-street-pole', 'Street Pole Banner (24×60")', "Standard street/light pole banner at 24×60\" with bleed for pole pocket.",
      [S('resize', { sheetWIn: 24, sheetHIn: 60, addMarks: true, centerMarks: true })]),
    e('lf-bus-shelter', 'Bus Shelter Poster (46×67")', "Standard bus shelter/transit advertising poster at 46×67\" for backlit display.",
      [S('resize', { sheetWIn: 46, sheetHIn: 67, addMarks: true, centerMarks: true })]),
    e('lf-yardsign-2418', 'Yard Sign (24×18")', "Standard coroplast yard sign at 24×18\" landscape for real estate, political, and event signage.",
      [S('resize', { sheetWIn: 24, sheetHIn: 18, addMarks: true, centerMarks: true })]),
    e('lf-feather-flag', 'Feather Flag (Soft Signage)', 'Feather-flag soft-signage panel scaled to the flag profile.',
      [S('resize', { sheetWIn: 30, sheetHIn: 100, addMarks: true, centerMarks: true })]),
  ] },

  // ── Office (30) ────────────────────────────────────────────────────────────
  { name: 'Office', entries: [
    e('of-2sided-a5', '2-Sided A5 Flyer', "Quick double-sided A5 flyer from your desktop printer. No marks, no bleeds — just fold or cut.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 8, cellHIn: 5.3, duplex: true, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-mini-a7-zine', 'Mini Booklet (A7 Zine)', "DIY mini zine using 4-up saddle-stitch on A4. Cut, fold, staple — instant pocket booklet.",
      [S('zine')]),
    e('of-greeting-a5', 'Greeting Card (A5 Fold)', "Single-fold greeting card on Letter landscape. Print, fold in half, done.",
      [S('booklet', { addMarks: true })]),
    e('of-4up-index', '4-Up Index Cards (3×5")', "Study flashcards or index cards, 4-up on Letter for cutting.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 5, cellHIn: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('cuttermarks', { cornersAndEdges: true })]),
    e('of-halfsheet-2up', 'Half-Sheet Handout 2-Up', "Two half-letter handouts per sheet. Perfect for meeting agendas, sign-up sheets, and flyers.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 8.5, cellHIn: 5.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-mailing-5160', 'Mailing Labels (Avery 5160 Style)', "Address labels nested on Letter. Compatible with Avery 5160 and similar 30-up label sheets.",
      [S('grid', { cols: 3, rows: 10, cellWIn: 2.625, cellHIn: 1, sheetWIn: 8.5, sheetHIn: 11, addMarks: true })]),
    e('of-add-pagenums', 'Add Page Numbers', "Adds \"Page X of Y\" to every page. Simple and universal — works with any PDF.",
      [S('pagenumbers')]),
    e('of-2up-proof-tab', '2-Up Proofing on Tabloid', "Proof Letter-size artwork 2-up on Tabloid with crop marks to verify bleed and trim.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('watermark', { text: 'PROOF' })]),
    e('of-rotate-landscape', 'Rotate All Pages Landscape', "Rotates all pages 90° clockwise. Useful for converting portrait scans to landscape.",
      [S('rotate', { angleDeg: 90 })]),
    e('of-interleave', 'Interleave Two Documents', 'Interleave the pages of two PDFs one after another.',
      [S('mix')]),
    e('of-tent-cards-4', 'Tent Cards (4-Up)', "Table tent cards (5×5\" flat, folds to 5×2.5\") printed 4-up on Letter.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 3.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-name-badges-8', 'Name Badges (8-Up)', "Conference name badges (3.5×2.25\") printed 8-up on Letter for badge holders.",
      [S('grid', { cols: 2, rows: 4, cellWIn: 3.5, cellHIn: 2.25, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-raffle-8up', 'Raffle Tickets (8-Up)', "Numbered raffle tickets (2×5.5\") printed 8-up on Letter with perforation marks.",
      [S('grid', { cols: 2, rows: 4, cellWIn: 4, cellHIn: 2.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-bookmarks-6', 'Bookmarks (6-Up)', "Standard bookmarks (2×6\") printed 6-up on Letter stock.",
      [S('grid', { cols: 6, rows: 1, cellWIn: 1.75, cellHIn: 7.5, sheetWIn: 11, sheetHIn: 8.5, addMarks: true, centerMarks: true })]),
    e('of-door-signs-2', 'Door Signs (2-Up)', "Do Not Disturb / office door signs (4×10\") printed 2-up on Letter.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 8.5, cellHIn: 5.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-deskplates-4', 'Desk Name Plates (4-Up)', "Folding desk name plates (8×2\" flat) printed 4-up on Letter.",
      [S('grid', { cols: 1, rows: 4, cellWIn: 8, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-parking-4', 'Parking Permits (4-Up)', "Parking permits / hang tags (3.5×5\") printed 4-up on Letter stock.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-visitor-10', 'Visitor Passes (10-Up)', "Business-card-size visitor passes (3.5×2\") printed 10-up on Letter stock.",
      [S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-flashcards-12', 'Flash Cards (12-Up)', "Study flash cards (3.5×2\") printed 12-up on Letter. Perfect for students and educators.",
      [S('grid', { cols: 3, rows: 4, cellWIn: 2.5, cellHIn: 2.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-recipe-46', 'Recipe Cards (4×6")', "Standard recipe cards (4×6\") printed 4-up on Tabloid. Double-sided for ingredients + instructions.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 6, cellHIn: 4, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-shipping-6', 'Shipping Labels (6-Up)', "Shipping/mailing labels (4×3.33\") printed 6-up on Letter. Fits standard label sheets.",
      [S('grid', { cols: 2, rows: 3, cellWIn: 4, cellHIn: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-place-cards-8', 'Place Cards (8-Up)', "Event place cards (3.5×2\") printed 8-up on Letter. Fold in half for tent-style seating cards.",
      [S('grid', { cols: 2, rows: 4, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-luggage-6', 'Luggage Tags (6-Up)', "Luggage tags (2.5×4.25\") printed 6-up on Letter with crop marks for die cutting.",
      [S('grid', { cols: 2, rows: 3, cellWIn: 2, cellHIn: 4, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-emergency-10', 'Emergency Contact Cards (10-Up)', "Wallet-size emergency contact cards (3.5×2\") printed 10-up on Letter.",
      [S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-spine-labels-10', 'Binder Spine Labels (10-Up)', "1\" binder spine labels printed 10-up on Letter. Standard 3-ring binder spine width.",
      [S('grid', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 1, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('of-certs-2', 'Certificates (2-Up)', "Half-letter classroom certificates printed 2-up on Letter for quick teacher printing.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true })]),
    e('of-draft-wm', 'Draft Watermark', "Stamp a diagonal DRAFT watermark on every page — prevents accidental use of unfinished documents.",
      [S('watermark', { text: 'DRAFT' })]),
    e('of-confidential-wm', 'Confidential Watermark', "Red CONFIDENTIAL watermark for sensitive documents — visible but non-destructive.",
      [S('watermark', { text: 'CONFIDENTIAL' })]),
    e('of-fullbleed-photocards', 'Full-Bleed Photo Cards (4×6")', 'Add bleed to 4×6" photo cards, then gang them 2-up (landscape) on Letter.',
      [S('bleed', { bleedIn: 0.125 }), S('grid', { cols: 1, rows: 2, cellWIn: 6, cellHIn: 4, sheetWIn: 8.5, sheetHIn: 11, bleedMode: 'fixed', bleedIn: 0.125, addMarks: true, centerMarks: true })]),
    e('of-proof-booklet-wm', 'Proof Booklet with Watermark', "Saddle-stitch booklet on Letter with a PROOF watermark — for client review copies.",
      [S('booklet', { addMarks: true }), S('watermark', { text: 'PROOF' })]),
  ] },

  // ── Variable Data (10) ─────────────────────────────────────────────────────
  { name: 'Variable Data', entries: [
    e('vd-event-qr', 'Event Tickets (QR Code)', "QR code tickets from CSV data, 2-up on Letter sheets for easy cutting.",
      [S('datamerge', { cols: 2, rows: 4, cellWIn: 4, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'qr' })]),
    e('vd-raffle-num', 'Raffle Tickets (Numbered)', "Code 128 barcode raffle tickets from CSV, 4-up on Letter.",
      [S('datamerge', { cols: 2, rows: 4, cellWIn: 4, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'code128' })]),
    e('vd-conf-badges-qr', 'Conference Badges (QR)', "Name badges with unique QR codes from CSV, 4-up on A4.",
      [S('datamerge', { cols: 2, rows: 4, cellWIn: 3.5, cellHIn: 2.25, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'qr' })]),
    e('vd-shipping-c128', 'Shipping Labels (Code 128)', "Shipping labels with unique Code 128 barcodes, 10-up on Letter.",
      [S('datamerge', { cols: 2, rows: 3, cellWIn: 4, cellHIn: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'code128' })]),
    e('vd-asset-dm', 'Asset Tags (DataMatrix)', "Compact DataMatrix asset tags, 10-up on Letter for inventory tracking.",
      [S('datamerge', { cols: 3, rows: 8, cellWIn: 2, cellHIn: 1, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'datamatrix' })]),
    e('vd-product-ean13', 'Product Labels (EAN-13)', "EAN-13 retail barcodes from CSV, 12-up on A4 for product labelling.",
      [S('datamerge', { cols: 2, rows: 5, cellWIn: 3, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'ean13' })]),
    e('vd-gift-qr', 'Gift Vouchers (QR Code)', "Gift vouchers with unique QR redemption codes, 2-up on A4.",
      [S('datamerge', { cols: 2, rows: 4, cellWIn: 4, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'qr' })]),
    e('vd-parking-qr', 'Parking Permits (QR Code)', "Parking permits with unique QR validation codes, 4-up on Letter.",
      [S('datamerge', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'qr' })]),
    e('vd-loyalty-c128', 'Loyalty Cards (Code 128)', "Loyalty/membership cards with unique Code 128 barcodes, 10-up on Letter.",
      [S('datamerge', { cols: 2, rows: 5, cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'code128' })]),
    e('vd-wristbands-qr', 'Wristbands (QR Code)', "Event wristbands with unique QR codes, 8-up on Letter.",
      [S('datamerge', { cols: 1, rows: 8, cellWIn: 10, cellHIn: 1, sheetWIn: 11, sheetHIn: 11, addMarks: true, centerMarks: true }), S('barcode', { symbology: 'qr' })]),
  ] },

  // ── Real Estate (5) ────────────────────────────────────────────────────────
  { name: 'Real Estate', entries: [
    e('re-justlisted-4up', 'Just-Listed Flyer 4-Up (4.25×5.5")', "Quarter-sheet just-listed flyers, 4-up on Letter — the cheapest way to print open-house handouts.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 4.25, cellHIn: 5.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('re-justlisted-2up', 'Just-Listed Flyer 2-Up (8.5×5.5")', "Half-sheet landscape just-listed flyers, 2-up on Letter for feature sheets and open-house handouts.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 8.5, cellHIn: 5.5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true, centerMarks: true })]),
    e('re-justsold-4up', 'Just-Sold Postcard 4-Up (4×6")', "USPS-standard 4×6\" just-sold / farming postcards, 4-up on Tabloid for short-run direct mail.",
      [S('grid', { cols: 2, rows: 2, cellWIn: 4, cellHIn: 6, sheetWIn: 13, sheetHIn: 19, addMarks: true, centerMarks: true })]),
    e('re-brochure-trifold', 'Property Brochure Tri-Fold 2-Up', 'Property tri-fold brochures (11×8.5") 2-up on Tabloid with fold marks.',
      [S('grid', { cols: 1, rows: 2, cellWIn: 11, cellHIn: 8.5, sheetWIn: 11, sheetHIn: 17, addMarks: true, centerMarks: true }), S('foldmarks', { scheme: 'trifold' })]),
    e('re-openhouse-yard', 'Open-House Yard Sign 2-Up (18×24")', "Two 18×24\" open-house / for-sale yard signs ganged on a 36×24\" large-format sheet.",
      [S('grid', { cols: 1, rows: 2, cellWIn: 18, cellHIn: 24, sheetWIn: 18, sheetHIn: 48, addMarks: true, centerMarks: true })]),
  ] },
];
