import { badRequest, json, unauthorized } from '@/lib/http';
import { getCurrentAdmin } from '@/lib/auth';
import { countAdmins, deleteUser, findUserById, setUserPassword, setUserPlan, setUserRole, setUserStatus } from '@/lib/users';
import { clearManualSubscription, setManualSubscription } from '@/lib/subscriptions';

const SUB_STATUSES = ['ACTIVE', 'CANCELLED', 'SUSPENDED', 'EXPIRED'];

export async function PATCH(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const admin = await getCurrentAdmin();
  if (!admin) return unauthorized();
  const { id } = await params;
  const userId = Number(id);
  const target = findUserById(userId);
  if (!target) return badRequest('User not found.');

  const body = await req.json().catch(() => ({}));

  // Guard: an admin cannot suspend or demote themselves via this endpoint.
  if (userId === admin.id && (body.status === 'suspended' || body.role === 'user')) {
    return badRequest('You cannot suspend or demote your own admin account.');
  }

  /* PASSWORD RESET. Admin-set, either typed or generated by the caller — the
     generator lives in the browser so the value reaches this endpoint the same
     way a typed one does, and there is exactly one code path to reason about.

     Deliberately NOT echoed back in the response: the admin already knows what
     they sent, and returning it would put the plaintext into a second place
     (server logs, proxy logs, the browser's network tab history) for no gain.
     The same minimum as signup, so an admin cannot set a password the user
     could not have chosen themselves. */
  if (typeof body.password === 'string') {
    const pw = body.password;
    if (pw.length < 8) return badRequest('Password must be at least 8 characters.');
    if (pw.length > 200) return badRequest('Password must be 200 characters or fewer.');
    await setUserPassword(userId, pw);
    /* Nothing else is applied in the same request: a reset is its own action,
       and mixing it with a plan or role change makes the audit trail ambiguous
       about what an admin actually did. */
    return json({ ok: true, passwordChanged: true });
  }

  if (body.plan === 'free' || body.plan === 'pro') setUserPlan(userId, body.plan);
  if (body.role === 'user' || body.role === 'admin') setUserRole(userId, body.role);
  if (body.status === 'active' || body.status === 'suspended') setUserStatus(userId, body.status);

  // Subscription grant/edit. `subscription: 'none'` removes any manual grant;
  // 'ACTIVE' with no endDate = lifetime (free-forever) comp; with endDate = a
  // timed comp. Other statuses drop the user to free.
  if (typeof body.subscription === 'string') {
    if (body.subscription === 'none') {
      clearManualSubscription(userId);
    } else if (SUB_STATUSES.includes(body.subscription)) {
      const end = body.subscriptionEndDate ? Date.parse(body.subscriptionEndDate) : null;
      setManualSubscription(userId, body.subscription, Number.isNaN(end as number) ? null : end);
    } else {
      return badRequest('Invalid subscription status.');
    }
  }

  return json({ ok: true });
}

/* Permanently delete a user. Their subscriptions and API keys cascade away and
   their usage_events keep their history with user_id nulled — see deleteUser.

   Two refusals, both about locking yourself out rather than about data:
   an admin cannot delete their own account, and the LAST admin cannot be
   deleted by anyone, because either leaves nobody able to reach this page. */
export async function DELETE(
  _req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const admin = await getCurrentAdmin();
  if (!admin) return unauthorized();
  const { id } = await params;
  const userId = Number(id);
  const target = findUserById(userId);
  if (!target) return badRequest('User not found.');

  if (userId === admin.id) return badRequest('You cannot delete your own admin account.');
  if (target.role === 'admin' && countAdmins() <= 1) {
    return badRequest('That is the last admin account — promote another admin first.');
  }

  deleteUser(userId);
  return json({ ok: true, deleted: true });
}
